export const AUDIT_ACTIONS = {
  WEBHOOK_RECEIVED: 'WEBHOOK_RECEIVED',
  WEBHOOK_PAYMENT_APPROVED: 'WEBHOOK_PAYMENT_APPROVED',
  WEBHOOK_PAYMENT_PENDING: 'WEBHOOK_PAYMENT_PENDING',
  WEBHOOK_PAYMENT_REJECTED: 'WEBHOOK_PAYMENT_REJECTED',
  RESERVATION_UPDATE_OK: 'RESERVATION_UPDATE_OK',
  RESERVATION_UPDATE_ERROR: 'RESERVATION_UPDATE_ERROR',
  EMAIL_CONFIRMATION_OK: 'EMAIL_CONFIRMATION_OK',
  EMAIL_CONFIRMATION_ERROR: 'EMAIL_CONFIRMATION_ERROR',
  WEBHOOK_ERROR: 'WEBHOOK_ERROR',
} as const;
